[package]
name = "ktn"
version = "0.1.3"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dotenv = "0"
dotenv_codegen = "0"
rusqlite = "0"
r2d2_sqlite = "0"
r2d2 = "0"