[package]
name = "ktn"
version = "0.1.8"
edition = "2021"

[dependencies]
askama = "0.12"
axum = "0.8"
chrono = "0"
dotenvy = "0.15"
mailparse = "0"
rand = "0.8"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-rustls", "postgres", "migrate"] }
thiserror = "2"
tracing = "0"
tracing-subscriber = { version = "0", features = ["fmt", "env-filter", "json"] }
tracing-log = "0"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["rt"] }
tower = "0"
tower-http = { version = "0.6", features = ["compression-full", "trace", "fs", "set-header"] }

[features]
tracing_json = []
tracing_noansi = []
