app = "ktnrs"
primary_region = "sjc"

kill_signal = "SIGTERM"
kill_timeout = "5s"

[env]
  WEB_URL = "https://ktnrs.com"
  EMAIL_DOMAIN = "ktnrs.com"
  STATIC_FOLDER = "/usr/local/share/ktn/static"
  HTTP_PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "connections"
    hard_limit = 500
    soft_limit = 200

[[services]]
  internal_port = 2525
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true

  [services.concurrency]
    type = "connections"
    hard_limit = 500
    soft_limit = 200

  [[services.ports]]
    port = 25

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "120s"
    timeout = "2s"

[[vm]]
  size = "shared-cpu-1x"
